CREATE TRIGGER TRG_DEPARTMENTS_NO_DELETE
ON DEPARTMENTS
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM DOCTORS 
        WHERE DEPID IN (SELECT DEPARTMENT_ID FROM deleted)
    )
    BEGIN
        RAISERROR ('Cannot delete department: Doctors assigned to it.', 16, 1);
        RETURN;
    END

    DELETE FROM DEPARTMENTS
    WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM deleted);
END;
GO


CREATE TRIGGER TRG_PATIENTS_NO_DELETE
ON PATIENTS
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM APPOINTMENTS
        WHERE PID IN (SELECT PATIENT_ID FROM deleted)
    )
    BEGIN
        RAISERROR('Cannot delete patient because there are appointments linked.', 16, 1);
        RETURN;
    END

    DELETE FROM PATIENTS
    WHERE PATIENT_ID IN (SELECT PATIENT_ID FROM deleted);
END;
GO



CREATE TRIGGER TRG_DOCTORS_NO_DELETE
ON DOCTORS
INSTEAD OF DELETE
AS
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM MEDICALRECORDS
        WHERE DID IN (SELECT DOCTOR_ID FROM deleted)
    )
    BEGIN
        RAISERROR('Cannot delete doctor because medical records are linked.', 16, 1);
        RETURN;
    END

    DELETE FROM DOCTORS
    WHERE DOCTOR_ID IN (SELECT DOCTOR_ID FROM deleted);
END;
GO


CREATE TRIGGER TRG_DEPARTMENTS_FORMAT
ON DEPARTMENTS
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE DEPARTMENTS
    SET DEPARTMENT_NAME = UPPER(DEPARTMENT_NAME)
    WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM inserted);
END;
GO


CREATE TRIGGER TRG_PATIENTS_EMAIL_FORMAT
ON PATIENTS
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE PATIENTS
    SET EMAIL = LOWER(EMAIL)
    WHERE PATIENT_ID IN (SELECT PATIENT_ID FROM inserted);
END;
GO


CREATE TRIGGER TRG_DOCTORS_SPEC_FORMAT
ON DOCTORS
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE DOCTORS
    SET SPECIALIZATION = UPPER(SPECIALIZATION)
    WHERE DOCTOR_ID IN (SELECT DOCTOR_ID FROM inserted);
END;
GO

CREATE TRIGGER TRG_APPOINTMENTS_NO_PAST
ON APPOINTMENTS
FOR INSERT
AS
BEGIN
    IF EXISTS (
        SELECT 1 FROM inserted WHERE APPOINTMENT_DATE < GETDATE()
    )
    BEGIN
        RAISERROR('Appointment cannot be scheduled in the past.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END
END;
GO


CREATE TRIGGER TRG_APPOINTMENTS_SET_STATUS
ON APPOINTMENTS
AFTER INSERT
AS
BEGIN
    UPDATE APPOINTMENTS
    SET STATUS = 'Scheduled'
    WHERE STATUS IS NULL
    AND APPOINTMENT_ID IN (SELECT APPOINTMENT_ID FROM inserted);
END;
GO


CREATE TABLE APPOINTMENT_LOG (
    LOG_ID INT IDENTITY PRIMARY KEY,
    APPOINTMENT_ID INT,
    ACTION VARCHAR(20),
    ACTION_DATE DATETIME DEFAULT GETDATE()
);
GO


CREATE TRIGGER TRG_APPOINTMENTS_AUDIT
ON APPOINTMENTS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    INSERT INTO APPOINTMENT_LOG (APPOINTMENT_ID, ACTION)
    SELECT APPOINTMENT_ID, 'INSERT' FROM inserted;

    INSERT INTO APPOINTMENT_LOG (APPOINTMENT_ID, ACTION)
    SELECT APPOINTMENT_ID, 'DELETE' FROM deleted;

    IF EXISTS (SELECT * FROM inserted) AND EXISTS (SELECT * FROM deleted)
    BEGIN
        INSERT INTO APPOINTMENT_LOG (APPOINTMENT_ID, ACTION)
        SELECT APPOINTMENT_ID, 'UPDATE' FROM inserted;
    END
END;
GO


CREATE TRIGGER TRG_BILLINGS_SET_STATUS
ON BILLINGS
AFTER INSERT
AS
BEGIN
    UPDATE BILLINGS
    SET STATUS = 'Unpaid'
    WHERE STATUS IS NULL
    AND BILL_ID IN (SELECT BILL_ID FROM inserted);
END;
GO


CREATE TRIGGER TRG_BILLINGS_NO_NEGATIVE
ON BILLINGS
FOR INSERT, UPDATE
AS
BEGIN
    IF EXISTS (SELECT 1 FROM inserted WHERE AMOUNT < 0)
    BEGIN
        RAISERROR('Bill amount cannot be negative.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END
END;
GO
